services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node-shibuya:
    image: subquerynetwork/subql-node-substrate:latest
    ports:
      - 3101:3101
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-shibuya.yaml
      - --multi-chain
      - --db-schema=lotto-multi-chain
      - --disable-historical
      - --skipTransactions
      - --port=3101
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3101/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-minato:
    image: subquerynetwork/subql-node-ethereum:latest
    ports:
      - 3102:3102
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app/project-minato.yaml
      - --multi-chain
      - --db-schema=lotto-multi-chain
      - --disable-historical
      - --skipTransactions
      - --port=3102
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3102/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-moonbase:
    image: onfinality/subql-node-ethereum:latest
    ports:
      - 3103:3103
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=app/project-moonbase.yaml
      - --multi-chain
      - --db-schema=lotto-multi-chain
      - --disable-historical
      - --skipTransactions
      - --port=3103
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3103/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3100:3100
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node-shibuya":
        condition: service_healthy
      "subquery-node-minato":
        condition: service_healthy
      "subquery-node-moonbase":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=lotto-multi-chain
      - --playground
      - --port=3100